### ISSUE TITLE
Indexing/Searching by License

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/knowledgegraph#1]
Hi all,

Firstly, lovely work at the webapp, I really enjoyed using both the webapp and the API, and looking forward to integrating it into the interative atlas viewer.

I understand the KG/Elastic Search is still at its infancy, some of what I am about to suggest may already be in the pipeline. apologies in advance. 

Would it be possible to have License be a node? i.e., indexable, searchable, but also contain attributes such as permalinks to conditions of use?

**Comment by olinux** [comment]
As in #3: Yes, this is definitively feasible if we have sufficient information to make it reasonable for the License to be a standalone search entity. Please note, that we have introduced "license" as a facet filter already: You can choose "Dataset" and then select the license you're interested in. For now, all datasets contain the same license, but if there are multiple, this would allow to distinct them. IMO, we should always think about if the entity is something a user explicitly looks for and wants to know something specific about it (=search entity) or if it is a selection criteria of another entity like "I would like to find all datasets with a creative commons license" (=filter criteria)

**Comment by olinux** [comment]
Update: the license now also contains the permalinks to conditions of use.
