### ISSUE TITLE
Searchable by atlas

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/knowledgegraph#3]
Currently, the atlas attribute contains a value, but distinctly, lacks a reference. 

I imagine, when multiple atlases becomes available, the atlas will be searchable, like authors, species, subjects, etc ...

**Comment by olinux** [comment]
There is always two "stages" of data being searchable: either as a property value of a "search entity" (such as authors, species, subjects, etc.) - and therefore potentially as a facet (in the left sidebar) or as a standalone entity and therefore a "result card". We currently follow the path to make sure that we only build entities containing enough information to be informative to the user. 
Over time, as more information is entered, we can think about creating a new search entity from it (which is quite easy to achieve btw)
